"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useSearchParams } from "next/navigation";
import Link from 'next/link';
import { MessageSquare, X, Send, Bot, Square, Trash2, ShieldAlert, Maximize2, Minimize2, Minus, ArrowRight } from "lucide-react";
import { useAssistantChat, type ChatMessage } from "@/hooks/useAssistantChat";
import { useSimulation } from "@/context/SimulationContext";
import { SUGGESTIONS } from "@/lib/assistant/knowledge";
import { cn } from "@/lib/utils";
import { WhatIfWidget } from "./WhatIfWidget";

function Bubble({ message, streaming }: { message: ChatMessage; streaming: boolean }) {
  const isUser = message.role === "user";

  if (isUser) {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] px-3 py-2 rounded-2xl rounded-br-sm bg-accent text-white text-sm whitespace-pre-wrap break-words">
          {message.content}
        </div>
      </div>
    );
  }

  if (message.content.includes("[WHAT_IF_ANALYSIS_UI]")) {
    return (
      <div className="flex justify-start flex-col gap-1 items-start w-full">
        <div className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl rounded-bl-sm p-4 w-full max-w-[88%] text-white shadow-md animate-in fade-in slide-in-from-bottom-2">
           <h4 className="font-bold text-lg mb-2 flex items-center gap-2"><Bot size={20} /> Scenario Simulation</h4>
           <p className="text-sm text-indigo-100 mb-4 leading-relaxed">
             I can help you simulate this scenario! I've prepared an interactive AI dashboard where we can tweak battery capacity, solar PV, and load to instantly calculate projected ROI, investments, and grid independence.
           </p>
           <Link href="/what-if" className="inline-flex items-center gap-2 bg-white text-indigo-600 px-4 py-2 rounded-xl text-sm font-bold shadow-sm hover:shadow hover:-translate-y-0.5 transition-all w-full justify-center">
             Open What-If Simulator <ArrowRight size={16} />
           </Link>
        </div>
        {message.model && !streaming && !message.error && (
          <div className="text-[9.5px] font-medium text-secondary-text/80 pl-2">
            Generated by {message.model.startsWith('Groq') ? 'Cloud AI' : 'Local AI'} ({message.model})
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="flex justify-start flex-col gap-1 items-start">
      <div
        className={cn(
          "max-w-[88%] px-3 py-2 rounded-2xl rounded-bl-sm text-sm whitespace-pre-wrap break-words border shadow-sm",
          message.error
            ? "bg-red-50 border-red-100 text-red-700"
            : message.refused
              ? "bg-amber-50 border-amber-100 text-amber-900"
              : "bg-white border-border text-primary-text",
        )}
      >
        {message.refused && (
          <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider mb-1 text-amber-600">
            <ShieldAlert size={12} /> Out of scope
          </div>
        )}
        {message.content || (streaming ? <TypingDots /> : null)}
      </div>
      {message.model && !streaming && !message.error && (
        <div className="text-[9.5px] font-medium text-secondary-text/80 pl-2">
          Generated by {message.model.startsWith('Groq') ? 'Cloud AI' : 'Local AI'} ({message.model})
        </div>
      )}
    </div>
  );
}

function TypingDots() {
  return (
    <span className="inline-flex items-center gap-1 py-0.5">
      <span className="w-1.5 h-1.5 rounded-full bg-secondary-text/60 animate-bounce" style={{ animationDelay: "0ms" }} />
      <span className="w-1.5 h-1.5 rounded-full bg-secondary-text/60 animate-bounce" style={{ animationDelay: "120ms" }} />
      <span className="w-1.5 h-1.5 rounded-full bg-secondary-text/60 animate-bounce" style={{ animationDelay: "240ms" }} />
    </span>
  );
}

export function ChatbotWidget() {
  const [isOpen, setIsOpen] = useState(false);
  const [isFullScreen, setIsFullScreen] = useState(false);
  const [inputValue, setInputValue] = useState("");
  const { messages, isStreaming, model, provider, setProvider, send, stop, reset } = useAssistantChat();
  const { activeSimulations, notifications, emsState } = useSimulation();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const selectedPlant = searchParams?.get("plantName") ?? null;

  const runtimeContext = useMemo(
    () => ({
      route: pathname,
      selectedPlant,
      activeSimulations: activeSimulations.map((s) => ({
        type: s.type,
        plantName: s.plantName,
        panelId: s.panelId,
        location: s.location,
        time: s.time,
        message: s.message,
      })),
      notifications: notifications.slice(0, 8).map((n) => ({
        title: n.title,
        message: n.message,
        type: n.type,
        time: n.time,
        read: Boolean(n.read),
      })),
      emsState,
    }),
    [pathname, selectedPlant, activeSimulations, notifications, emsState],
  );

  useEffect(() => {
    if (isOpen) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isOpen]);

  useEffect(() => {
    if (isOpen) inputRef.current?.focus();
  }, [isOpen]);

  const handleSend = (e: React.FormEvent) => {
    e.preventDefault();
    const value = inputValue.trim();
    if (!value || isStreaming) return;
    setInputValue("");
    void send(value, runtimeContext);
  };

  const handleSuggestion = (value: string) => {
    if (isStreaming) return;
    void send(value, runtimeContext);
  };

  const isEmpty = messages.length === 0;

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        aria-label="Open ENECO Assistant"
        className={cn(
          "fixed bottom-6 right-6 w-14 h-14 bg-accent-dark text-white rounded-full shadow-lg flex items-center justify-center hover:scale-110 hover:shadow-xl transition-all duration-300 z-50 cursor-pointer",
          isOpen ? "scale-0 opacity-0 pointer-events-none" : "scale-100 opacity-100",
        )}
      >
        <MessageSquare size={24} />
        {activeSimulations.length > 0 && (
          <span className="absolute -top-1 -right-1 min-w-[20px] h-5 px-1 flex items-center justify-center bg-danger text-white text-[10px] font-bold rounded-full border-2 border-white">
            {activeSimulations.length}
          </span>
        )}
      </button>

      <div
        className={cn(
          "bg-surface border-border flex flex-col overflow-hidden z-50 transition-all duration-300 shadow-2xl",
          isFullScreen 
            ? "fixed inset-0 w-full h-full rounded-none" 
            : "fixed bottom-6 right-6 w-[22rem] h-[30rem] max-w-[calc(100vw-2rem)] rounded-2xl border origin-bottom-right",
          isOpen ? "scale-100 opacity-100" : "scale-0 opacity-0 pointer-events-none",
        )}
      >
        <div className="bg-accent-dark text-white px-4 py-3 flex justify-between items-center gap-2">
          <div className="flex items-center gap-2 min-w-0">
            <Bot size={20} className="shrink-0" />
            <div className="min-w-0">
              <div className="font-bold text-sm leading-tight truncate">ENECO Assistant</div>
              <div className="flex items-center gap-2 mt-0.5">
                <div className="text-[10px] font-medium opacity-80 truncate max-w-[120px]" title={model || (provider === "groq" ? "Cloud AI Ready" : "Local AI Ready")}>
                  {model ? model : (provider === "groq" ? "Cloud AI Ready" : "Local AI Ready")}
                </div>
                <select 
                  value={provider}
                  onChange={(e) => setProvider(e.target.value as "groq" | "ollama")}
                  className="bg-accent text-white border border-white/20 text-[10px] rounded px-1 py-0.5 outline-none cursor-pointer"
                  disabled={isStreaming}
                >
                  <option value="groq">Groq (Cloud)</option>
                  <option value="ollama">Ollama (Local)</option>
                </select>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-1 shrink-0">
            {!isEmpty && (
              <button
                onClick={reset}
                disabled={isStreaming}
                aria-label="Clear conversation"
                className="hover:bg-white/20 p-1.5 rounded-md transition-colors disabled:opacity-40 cursor-pointer"
                title="Clear Chat"
              >
                <Trash2 size={16} />
              </button>
            )}
            <button
              onClick={() => setIsFullScreen(!isFullScreen)}
              aria-label="Toggle Full Screen"
              className="hover:bg-white/20 p-1.5 rounded-md transition-colors cursor-pointer"
              title={isFullScreen ? "Exit Full Screen" : "Full Screen"}
            >
              {isFullScreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
            </button>
            <button
              onClick={() => setIsOpen(false)}
              aria-label="Minimize assistant"
              className="hover:bg-white/20 p-1.5 rounded-md transition-colors cursor-pointer"
              title="Minimize"
            >
              <Minus size={18} />
            </button>
          </div>
        </div>

        <div ref={scrollRef} className="flex-1 px-3 py-3 overflow-y-auto flex flex-col gap-2.5 bg-gray-50/50">
          {isEmpty ? (
            <div className="flex flex-col gap-3 py-2">
              <div className="px-3 py-2 rounded-2xl rounded-bl-sm bg-white border border-border text-sm shadow-sm text-primary-text">
                Hello! I am the ENECO Assistant. I answer only from live plant data — generation, PR and soiling, battery health, grid tariffs and savings, forecasts, events and reports.
              </div>
              <div className="px-3 py-2 rounded-xl bg-amber-50 border border-amber-100 text-[11px] text-amber-800">
                Out of subject questions — code, general maths, trivia — I decline on purpose.
              </div>
              <div className="flex flex-col gap-1.5 mt-1">
                {SUGGESTIONS.map((s) => (
                  <button
                    key={s}
                    onClick={() => handleSuggestion(s)}
                    className="text-left px-3 py-2 rounded-xl bg-white border border-border text-xs font-medium text-secondary-text hover:border-accent hover:text-accent-dark transition-colors cursor-pointer"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((msg) => (
              <Bubble
                key={msg.id}
                message={msg}
                streaming={isStreaming && msg.role === "assistant" && msg.content.length === 0}
              />
            ))
          )}
        </div>

        <form onSubmit={handleSend} className="p-3 border-t border-border bg-surface flex items-center gap-2">
          <input
            ref={inputRef}
            type="text"
            placeholder="Ask about generation, PR, battery, savings..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            maxLength={600}
            className="flex-1 border border-border rounded-full px-4 py-2 text-sm outline-none focus:border-accent focus:ring-1 focus:ring-accent transition-all bg-white"
          />
          {isStreaming ? (
            <button
              type="button"
              onClick={stop}
              aria-label="Stop generating"
              className="w-10 h-10 rounded-full bg-primary-text text-white flex items-center justify-center hover:bg-black transition-colors shrink-0 cursor-pointer"
            >
              <Square size={14} fill="currentColor" />
            </button>
          ) : (
            <button
              type="submit"
              disabled={!inputValue.trim()}
              aria-label="Send message"
              className="w-10 h-10 rounded-full bg-accent text-white flex items-center justify-center hover:bg-accent-dark transition-colors shrink-0 disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
            >
              <Send size={16} className="-ml-0.5" />
            </button>
          )}
        </form>
      </div>
    </>
  );
}
